### ISSUE TITLE
can't connect maid fiddler gui to com3d2

### ISSUE THREAD

**Issue by snkagawa** [ghorsington/COM3D2.MaidFiddler#52]
can't connect maid fiddler gui to com3d2. 
![err](https://user-images.githubusercontent.com/10864635/95044728-c0c6ec80-0712-11eb-8b3c-aea803e96a41.jpg)

already update com3d2 (1.52) and maid fiddler (1.8.1) to latest version

have this error on com3d console 
![error](https://user-images.githubusercontent.com/10864635/95044675-9bd27980-0712-11eb-8fde-6b67e64f885e.jpg)

download from : https://sukebei.nyaa.si/view/3063397 and https://sukebei.nyaa.si/view/3037766

**Comment by Tenebra233** [comment]
> can't connect maid fiddler gui to com3d2.
> ![err](https://user-images.githubusercontent.com/10864635/95044728-c0c6ec80-0712-11eb-8b3c-aea803e96a41.jpg)
> 
> already update com3d2 (1.52) and maid fiddler (1.8.1) to latest version
> 
> have this error on com3d console
> ![error](https://user-images.githubusercontent.com/10864635/95044675-9bd27980-0712-11eb-8fde-6b67e64f885e.jpg)
> 
> download from : https://sukebei.nyaa.si/view/3063397 and https://sukebei.nyaa.si/view/3037766

Maid fiddler is not updated for this game version, that's why it's not connecting
